name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 2222
          script: |
            cd /home/ita/Apps/DisCo
            git pull origin master
            /home/ita/Apps/DisCo/.venv/bin/pip install -r requirements.txt
            sudo systemctl restart disco
